### ISSUE TITLE
End-to-End Performance

### ISSUE THREAD

**Issue by DSpeckhals** [DSpeckhals/python-indent#24]
Overall, thanks to the routines in this package only being executed at a new line event, performance doesn't seem to be a big issue. However, I have noticed a couple of times (especially in large files), where I notice a sub-second blip when on `enter`. This may or may not be due to this actual package, but I think it would be good to create some "wild" test scenarios and see if any improvements can be made.

**Comment by kbrose** [comment]
Some thoughts:

Maybe we could try and use some cacheing? E.g., if only code on line > 150 has been changed, then the `openBracketStack` as it was for lines 0-150 will still be the same the next time you press Enter, so if we had cached the value of openBracketStack (and I guess all the other stateful variables, e.g. are we in a string, is it a triple quoted string, etc.) as it was on line 150, then we could start processing only from there down.

This might combine well with actually having it run _more_ often than just on "enter" events, i.e. every **x** milliseconds (where **x** could be configurable), so that you can keep your cache more up to date.

**Comment by kbrose** [comment]
The open bracket stack is theoretically unbounded in size, but would take **_a lot**_ of open brackets in order to even break into the megabytes. Still, something to think about.

**Comment by DSpeckhals** [comment]
Closing...if the need presents itself, we'll take care of it.
