### ISSUE TITLE
Slow loading time?

### ISSUE THREAD

**Issue by danqing** [DSpeckhals/python-indent#38]
Hi,

First of all, great repo - thanks for it! I just want to mention that it's currently (by far) the slowest-loading plugin, at 687ms. The second slowest is only 24ms. I wonder if there's a bug or if there's anything that can be done about it?

I'm on atom 1.15, macOS 10.12.

Thanks!

**Comment by DSpeckhals** [comment]
That's odd. There nothing in the package itself that I can think of that would make it slow vs. other packages. I tested it out on a Windows and Linux machine, and most times, it loads in under 5ms. Maybe it was the first time the package was loaded on your instance of Atom. If that were the case, then it may be the transpile step when a package is first downloaded or updated.

Otherwise, the only thing python-indent does when it first opens is instantiate the `PythonIndent` prototype and attach an Atom internal event listener (`editor:newline`) to the `PythonIndent.indent` method. Most packages do something like this when they start up.

Let me know if this happens consistently.

**Comment by danqing** [comment]
Oh you are right. I rebooted my laptop and now it's doing fine.

Thanks again!
