### ISSUE TITLE
Indent size of 2

### ISSUE THREAD

**Issue by armancohan** [DSpeckhals/python-indent#41]
Is there a way to change the indent size to 2?

**Comment by DSpeckhals** [comment]
Do you mean 2 tabs or 2 spaces?

You can change between one and two tabs (most people will expand tabs to spaces, which would translate to four or eight spaces) in the settings for this package; the PEP8 Style allows for this.

As for two spaces, I guess this would depend on the language settings you have for Python: it might work. However, I don't plan on supporting two spaces, because it goes against the [PEP8 Style Guide](https://www.python.org/dev/peps/pep-0008/#indentation), and this package adapts strictly to that style guide.

Either of these settings would only affect a hanging indent like this:

```python
def test_function(
    |
```

**Comment by armancohan** [comment]
I understand that indent size of 4 spaces is according to PEP8.
But there are some rather popular styles that are according to PEP8 but use the indent size of 2.
Google python style is one example: https://developers.google.com/edu/python/introduction
So, it would be great to have support for indent size of 2 spaces.

**Comment by DSpeckhals** [comment]
This is not something this package can actually fix. There's nothing in this packages code that cares about what the current tab expansion setting is. The problem is an underlying bug in atom-settings-view where you can't use 2 spaces for Python:

https://github.com/atom/language-python/issues/175

**Comment by kbrose** [comment]
Unfortunate situation, but it looks like this issue should probably be closed? Unless you think there's more to do in this repo @acohan?
