### ISSUE TITLE
No newline created when text already on next line

### ISSUE THREAD

**Issue by kbrose** [DSpeckhals/python-indent#5]
Create a python file that has three lines:

``` python
l = [0, 1, 2, 3]
l2 = map(
x = 1.0
```

Hit enter on the second line, after `map(`, and instead of creating a new line with the proper indentation, the line containing `x = 1.0` is indented and no newline is created.

Using python indent version 0.3.3, Atom version 1.5.3

**Comment by DSpeckhals** [comment]
Thanks for the example. There is some improvement still that can be done to make the hanging indentation behavior better; this is a good start. I'll push out the change that fixes this soon.

Another thing that is a little more complicated is what Atom does with bracket matching in this situation.

Take this example:

``` python
def test_this(<cursor here>)
```

Which places the closing paren like this:

``` python
def test_this(
    <cursor here>
)
```

This is because Atom's bracket matching package is trying to be clever. It's not so good for Python. I'm not sure if the bracket-matcher needs fixed in Python, or if I can shim it in this package (which is what I was trying to do with the bug you're experiencing). I think just doing what you're suggesting is the best for now.

**Comment by kbrose** [comment]
Thanks for the quick turn-around! I've noticed some other stuff going on that I hope to log as issues soon, but by no means do I just wish to dump a bunch of work in your lap. I haven't programmed in JS or coffeescript before, but I would be willing to give a shot at doing some PRs.
